version: "3"

services:
  web:
    container_name: web
    build: ./api
    ports:
      - 5000:5000
    links:
      - redis
    depends_on:
      - redis
    environment:
      - FLASK_ENV=development
    volumes:
      - ./api:/app

  redis:
    container_name: redis
    image: redis
    hostname: redis

  worker:
    build:
      context: ./api
    hostname: worker
    entrypoint: celery
    command: -A celery_app.celery worker --loglevel=info
    volumes:
      - ./api:/app
    links:
      - redis
    depends_on:
      - redis